### ISSUE TITLE
🔴 Before First Release TODO

### ISSUE THREAD

**Issue by Wulian233** [Wulian233/Chat-Impressive-Animation#2]
- [x] 🏗️ Port the latest version to 1.20-1.20.4 (Thanks @TexBlock ❤️)
- [x] 🌉 Redesign the mod icon
- [x] ✨ Rename the mod name and modid
 1. CIA: Chat Impressive Animation
 2. 聊动魅影
- [x] 🤔 Test
message indicator提示器于1.19.1加入

 1. Forge: 1.20.x放弃，无法修复：无消息淡入动画

- [x] ✍🏻 Write README.md
- [x] 🔄 Github action
- [x] 🔨 Create CurseForge and Modrinth project **(modrinth Unlisted)**
- - [x] CurseForge https://legacy.curseforge.com/minecraft/mc-mods/chat-impressive-animation
- - [x] Modrinth https://modrinth.com/project/chat-impressive-animation/
